# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(789, 600)
        MainWindow.setStyleSheet("background-color: #88acb8;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.note_text = QtWidgets.QTextEdit(self.centralwidget)
        self.note_text.setGeometry(QtCore.QRect(0, 90, 611, 481))
        self.note_text.setStyleSheet("background-color:#c8d1a3;\n"
"color: white;\n"
"border-radius:10px;")
        self.note_text.setObjectName("note_text")
        self.titel_note_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.titel_note_edit.setGeometry(QtCore.QRect(0, 30, 611, 41))
        self.titel_note_edit.setStyleSheet("background-color:#c8d1a3;\n"
"color: white;\n"
"border-radius:10px;")
        self.titel_note_edit.setObjectName("titel_note_edit")
        self.create_notes = QtWidgets.QPushButton(self.centralwidget)
        self.create_notes.setGeometry(QtCore.QRect(620, 30, 75, 23))
        self.create_notes.setStyleSheet("background-color: white;\n"
"color: #10c215;\n"
"border-radius:10px;")
        self.create_notes.setObjectName("create_notes")
        self.save_note = QtWidgets.QPushButton(self.centralwidget)
        self.save_note.setGeometry(QtCore.QRect(660, 60, 81, 31))
        self.save_note.setStyleSheet("background-color: white;\n"
"color: #10c215;\n"
"border-radius:10px;")
        self.save_note.setObjectName("save_note")
        self.list_notes = QtWidgets.QListWidget(self.centralwidget)
        self.list_notes.setGeometry(QtCore.QRect(630, 110, 131, 241))
        self.list_notes.setStyleSheet("background-color:#c8d1a3;\n"
"color: white;\n"
"border-radius:10px;")
        self.list_notes.setObjectName("list_notes")
        self.delete_notes = QtWidgets.QPushButton(self.centralwidget)
        self.delete_notes.setGeometry(QtCore.QRect(710, 30, 75, 23))
        self.delete_notes.setStyleSheet("background-color: white;\n"
"color: #10c215;\n"
"border-radius:10px;")
        self.delete_notes.setObjectName("delete_notes")
        self.tag_list = QtWidgets.QListWidget(self.centralwidget)
        self.tag_list.setGeometry(QtCore.QRect(630, 421, 131, 131))
        self.tag_list.setStyleSheet("background-color:#c8d1a3;\n"
"color: white;\n"
"border-radius:10px;")
        self.tag_list.setObjectName("tag_list")
        self.add_tag = QtWidgets.QPushButton(self.centralwidget)
        self.add_tag.setGeometry(QtCore.QRect(620, 360, 75, 23))
        self.add_tag.setStyleSheet("background-color: white;\n"
"color: #10c215;\n"
"border-radius:10px;")
        self.add_tag.setObjectName("add_tag")
        self.open_tag = QtWidgets.QPushButton(self.centralwidget)
        self.open_tag.setGeometry(QtCore.QRect(710, 360, 75, 23))
        self.open_tag.setStyleSheet("background-color: white;\n"
"color: #10c215;\n"
"border-radius:10px;")
        self.open_tag.setObjectName("open_tag")
        self.search_tag = QtWidgets.QPushButton(self.centralwidget)
        self.search_tag.setGeometry(QtCore.QRect(660, 390, 75, 23))
        self.search_tag.setStyleSheet("background-color: white;\n"
"color: #10c215;\n"
"border-radius:10px;")
        self.search_tag.setObjectName("search_tag")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 789, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.create_notes.setText(_translate("MainWindow", "Create"))
        self.save_note.setText(_translate("MainWindow", "Save"))
        self.delete_notes.setText(_translate("MainWindow", "Delete"))
        self.add_tag.setText(_translate("MainWindow", " Add Tag"))
        self.open_tag.setText(_translate("MainWindow", "Open Tag"))
        self.search_tag.setText(_translate("MainWindow", "Search Tag"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
